name: Deployment

on:
  push:
    branches: [ main ]

jobs:
  
  build:
    
    runs-on: ubuntu-latest

    steps:
      
    - name: Install Surge
      run: npm install --global surge
      
    - name: Run surge
      run: surge ./ https://resume-faizan.surge.sh --token ${{ secrets.SURGE_TOKEN }}
